# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(430, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 10, 351, 151))
        self.groupBox.setObjectName("groupBox")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(10, 100, 331, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.input_open_com = QtWidgets.QCommandLinkButton(self.frame)
        self.input_open_com.setGeometry(QtCore.QRect(20, 0, 101, 41))
        self.input_open_com.setObjectName("input_open_com")
        self.input_close_com = QtWidgets.QCommandLinkButton(self.frame)
        self.input_close_com.setGeometry(QtCore.QRect(170, 0, 131, 41))
        self.input_close_com.setObjectName("input_close_com")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 331, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_title_comunicao_serial = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_title_comunicao_serial.setFont(font)
        self.label_title_comunicao_serial.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_comunicao_serial.setObjectName("label_title_comunicao_serial")
        self.horizontalLayout.addWidget(self.label_title_comunicao_serial)
        self.label_serial_status = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_serial_status.setFont(font)
        self.label_serial_status.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_serial_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_serial_status.setObjectName("label_serial_status")
        self.horizontalLayout.addWidget(self.label_serial_status)
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setGeometry(QtCore.QRect(10, 60, 331, 41))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.input_update_com_ports = QtWidgets.QPushButton(self.frame_2)
        self.input_update_com_ports.setGeometry(QtCore.QRect(250, 10, 75, 23))
        self.input_update_com_ports.setObjectName("input_update_com_ports")
        self.input_com_port = QtWidgets.QComboBox(self.frame_2)
        self.input_com_port.setGeometry(QtCore.QRect(10, 10, 151, 22))
        self.input_com_port.setObjectName("input_com_port")
        self.input_baud_rate = QtWidgets.QComboBox(self.frame_2)
        self.input_baud_rate.setGeometry(QtCore.QRect(170, 10, 71, 22))
        self.input_baud_rate.setObjectName("input_baud_rate")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 170, 351, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 331, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_title_comunicao_vrep = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_title_comunicao_vrep.setFont(font)
        self.label_title_comunicao_vrep.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_comunicao_vrep.setObjectName("label_title_comunicao_vrep")
        self.horizontalLayout_2.addWidget(self.label_title_comunicao_vrep)
        self.label_vrep_status = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_vrep_status.setFont(font)
        self.label_vrep_status.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_vrep_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_vrep_status.setObjectName("label_vrep_status")
        self.horizontalLayout_2.addWidget(self.label_vrep_status)
        self.frame_3 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 60, 331, 41))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.input_connect_vrep = QtWidgets.QCommandLinkButton(self.frame_3)
        self.input_connect_vrep.setGeometry(QtCore.QRect(10, 0, 101, 41))
        self.input_connect_vrep.setObjectName("input_connect_vrep")
        self.input_disconnect_vrep = QtWidgets.QCommandLinkButton(self.frame_3)
        self.input_disconnect_vrep.setGeometry(QtCore.QRect(170, 0, 121, 41))
        self.input_disconnect_vrep.setObjectName("input_disconnect_vrep")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 290, 351, 271))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 50, 321, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input_joint_name = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.input_joint_name.setObjectName("input_joint_name")
        self.horizontalLayout_3.addWidget(self.input_joint_name)
        self.input_joint_id = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.input_joint_id.setObjectName("input_joint_id")
        self.horizontalLayout_3.addWidget(self.input_joint_id)
        self.input_joint_type = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.input_joint_type.setObjectName("input_joint_type")
        self.input_joint_type.addItem("")
        self.input_joint_type.addItem("")
        self.input_joint_type.addItem("")
        self.input_joint_type.addItem("")
        self.horizontalLayout_3.addWidget(self.input_joint_type)
        self.input_insert_joint = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.input_insert_joint.setObjectName("input_insert_joint")
        self.horizontalLayout_3.addWidget(self.input_insert_joint)
        self.input_remove_joint = QtWidgets.QPushButton(self.groupBox_3)
        self.input_remove_joint.setGeometry(QtCore.QRect(270, 240, 75, 23))
        self.input_remove_joint.setObjectName("input_remove_joint")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_4.setGeometry(QtCore.QRect(20, 20, 321, 21))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setGeometry(QtCore.QRect(20, 0, 76, 29))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(130, 0, 31, 29))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(180, 0, 41, 29))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.list_joints = QtWidgets.QTableWidget(self.groupBox_3)
        self.list_joints.setGeometry(QtCore.QRect(20, 90, 321, 141))
        self.list_joints.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list_joints.setAutoScroll(True)
        self.list_joints.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_joints.setTabKeyNavigation(True)
        self.list_joints.setProperty("showDropIndicator", True)
        self.list_joints.setDragEnabled(False)
        self.list_joints.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.list_joints.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.list_joints.setShowGrid(False)
        self.list_joints.setWordWrap(True)
        self.list_joints.setObjectName("list_joints")
        self.list_joints.setColumnCount(3)
        self.list_joints.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_joints.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_joints.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.list_joints.setHorizontalHeaderItem(2, item)
        self.list_joints.horizontalHeader().setVisible(True)
        self.list_joints.horizontalHeader().setCascadingSectionResizes(False)
        self.list_joints.horizontalHeader().setDefaultSectionSize(106)
        self.list_joints.horizontalHeader().setHighlightSections(True)
        self.list_joints.horizontalHeader().setSortIndicatorShown(False)
        self.list_joints.horizontalHeader().setStretchLastSection(False)
        self.list_joints.verticalHeader().setVisible(False)
        self.list_joints.verticalHeader().setCascadingSectionResizes(False)
        self.list_joints.verticalHeader().setDefaultSectionSize(19)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Libvrep Visual"))
        self.groupBox.setTitle(_translate("MainWindow", "Serial"))
        self.input_open_com.setText(_translate("MainWindow", "Conectar"))
        self.input_close_com.setText(_translate("MainWindow", "Desconectar"))
        self.label_title_comunicao_serial.setText(_translate("MainWindow", "Comunicação Serial"))
        self.label_serial_status.setText(_translate("MainWindow", "Desconectado"))
        self.input_update_com_ports.setText(_translate("MainWindow", "Atualizar"))
        self.input_baud_rate.setItemText(0, _translate("MainWindow", "9600"))
        self.input_baud_rate.setItemText(1, _translate("MainWindow", "19200"))
        self.input_baud_rate.setItemText(2, _translate("MainWindow", "38400"))
        self.input_baud_rate.setItemText(3, _translate("MainWindow", "57600"))
        self.input_baud_rate.setItemText(4, _translate("MainWindow", "74880"))
        self.input_baud_rate.setItemText(5, _translate("MainWindow", "115200"))
        self.input_baud_rate.setItemText(6, _translate("MainWindow", "230400"))
        self.input_baud_rate.setItemText(7, _translate("MainWindow", "250000"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Vrep"))
        self.label_title_comunicao_vrep.setText(_translate("MainWindow", "Comunicação Vrep"))
        self.label_vrep_status.setText(_translate("MainWindow", "Desconectado"))
        self.input_connect_vrep.setText(_translate("MainWindow", "Conectar"))
        self.input_disconnect_vrep.setText(_translate("MainWindow", "Desconectar"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Juntas"))
        self.input_joint_type.setItemText(0, _translate("MainWindow", "Revolute"))
        self.input_joint_type.setItemText(1, _translate("MainWindow", "Prismatic"))
        self.input_joint_type.setItemText(2, _translate("MainWindow", "Spherical"))
        self.input_joint_type.setItemText(3, _translate("MainWindow", "Motor"))
        self.input_insert_joint.setText(_translate("MainWindow", "Adicionar"))
        self.input_remove_joint.setText(_translate("MainWindow", "Remover"))
        self.label.setText(_translate("MainWindow", "Nome da Junta"))
        self.label_2.setText(_translate("MainWindow", "ID"))
        self.label_3.setText(_translate("MainWindow", "Tipo"))
        self.list_joints.setSortingEnabled(False)
        item = self.list_joints.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.list_joints.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ID"))
        item = self.list_joints.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tipo"))

