# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'screen.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(488, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 10, 351, 141))
        self.groupBox.setObjectName("groupBox")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(10, 90, 331, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.input_open_com = QtWidgets.QCommandLinkButton(self.frame)
        self.input_open_com.setGeometry(QtCore.QRect(20, 0, 101, 41))
        self.input_open_com.setObjectName("input_open_com")
        self.input_close_com = QtWidgets.QCommandLinkButton(self.frame)
        self.input_close_com.setGeometry(QtCore.QRect(170, 0, 131, 41))
        self.input_close_com.setObjectName("input_close_com")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 331, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_title_comunicao_serial = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_title_comunicao_serial.setFont(font)
        self.label_title_comunicao_serial.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_comunicao_serial.setObjectName("label_title_comunicao_serial")
        self.horizontalLayout.addWidget(self.label_title_comunicao_serial)
        self.label_serial_status = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_serial_status.setFont(font)
        self.label_serial_status.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_serial_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_serial_status.setObjectName("label_serial_status")
        self.horizontalLayout.addWidget(self.label_serial_status)
        self.frame_2 = QtWidgets.QFrame(self.groupBox)
        self.frame_2.setGeometry(QtCore.QRect(10, 50, 331, 41))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.input_update_com_ports = QtWidgets.QPushButton(self.frame_2)
        self.input_update_com_ports.setGeometry(QtCore.QRect(250, 10, 75, 23))
        self.input_update_com_ports.setObjectName("input_update_com_ports")
        self.input_com_port = QtWidgets.QComboBox(self.frame_2)
        self.input_com_port.setGeometry(QtCore.QRect(10, 10, 151, 22))
        self.input_com_port.setObjectName("input_com_port")
        self.input_baud_rate = QtWidgets.QComboBox(self.frame_2)
        self.input_baud_rate.setGeometry(QtCore.QRect(170, 10, 71, 22))
        self.input_baud_rate.setObjectName("input_baud_rate")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.input_baud_rate.addItem("")
        self.text_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_log.setGeometry(QtCore.QRect(20, 341, 451, 191))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.text_log.setFont(font)
        self.text_log.setMidLineWidth(0)
        self.text_log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.text_log.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.text_log.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.text_log.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.text_log.setTabStopWidth(80)
        self.text_log.setObjectName("text_log")
        self.input_parse = QtWidgets.QPushButton(self.centralwidget)
        self.input_parse.setGeometry(QtCore.QRect(20, 250, 75, 23))
        self.input_parse.setObjectName("input_parse")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 471, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.frame_3 = QtWidgets.QFrame(self.groupBox_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 20, 441, 41))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 441, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.input_select_file = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.input_select_file.setObjectName("input_select_file")
        self.horizontalLayout_2.addWidget(self.input_select_file)
        self.label_file_name = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.label_file_name.setObjectName("label_file_name")
        self.horizontalLayout_2.addWidget(self.label_file_name)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(20, 290, 101, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(150, 290, 161, 41))
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.commandLinkButton_3 = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton_3.setGeometry(QtCore.QRect(320, 290, 141, 41))
        self.commandLinkButton_3.setObjectName("commandLinkButton_3")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(200, 250, 218, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input_addr_plus_code = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.input_addr_plus_code.setObjectName("input_addr_plus_code")
        self.horizontalLayout_3.addWidget(self.input_addr_plus_code)
        self.input_only_code = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.input_only_code.setChecked(True)
        self.input_only_code.setObjectName("input_only_code")
        self.horizontalLayout_3.addWidget(self.input_only_code)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Serial"))
        self.input_open_com.setText(_translate("MainWindow", "Conectar"))
        self.input_close_com.setText(_translate("MainWindow", "Desconectar"))
        self.label_title_comunicao_serial.setText(_translate("MainWindow", "Comunicação Serial"))
        self.label_serial_status.setText(_translate("MainWindow", "Desconectado"))
        self.input_update_com_ports.setText(_translate("MainWindow", "Atualizar"))
        self.input_baud_rate.setItemText(0, _translate("MainWindow", "9600"))
        self.input_baud_rate.setItemText(1, _translate("MainWindow", "19200"))
        self.input_baud_rate.setItemText(2, _translate("MainWindow", "38400"))
        self.input_baud_rate.setItemText(3, _translate("MainWindow", "57600"))
        self.input_baud_rate.setItemText(4, _translate("MainWindow", "74880"))
        self.input_baud_rate.setItemText(5, _translate("MainWindow", "115200"))
        self.input_baud_rate.setItemText(6, _translate("MainWindow", "230400"))
        self.input_baud_rate.setItemText(7, _translate("MainWindow", "250000"))
        self.text_log.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.input_parse.setText(_translate("MainWindow", "Analisar"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Arquivo"))
        self.input_select_file.setText(_translate("MainWindow", "Abrir"))
        self.commandLinkButton.setText(_translate("MainWindow", "Carregar"))
        self.commandLinkButton_2.setText(_translate("MainWindow", "Apagar Memória"))
        self.commandLinkButton_3.setText(_translate("MainWindow", "Ler Memória"))
        self.input_addr_plus_code.setText(_translate("MainWindow", "Endereço + Código"))
        self.input_only_code.setText(_translate("MainWindow", "Apenas Código"))

